config/routes.rb
Rails.application.routes.draw do

  get 'dones/create'
devise_for :users, controllers: {
  registrations: 'users/registrations'
}

  resources :tasks do
    resources :dones, only: :create
  end



  resources :dones do
    member do
      post 'ruta_1', to: 'dones#validation'
    end
  end

  root to: 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/task.rb
class Task < ApplicationRecord
  has_many :dones
  has_many :users, through: :dones
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
        
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Se ha borrado una actividad.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<table>
  <tbody>
    <div class="container">
      <h1 class="center">Actividades para este 18 de septiembre</h1>
      <div  class="row">
        <% @tasks.each do |task| %>
          <div class="col-md-4 col-sm-1">
              <div class="card marginc">
               <%= image_tag task.photo, class: 'card-img-top' %>
                <div class="body">
                  <h3> <%= task.title %> </h3>
                  <p> <%= task.description %> </p>
                      <% if task.users.include?(current_user) %>
                          <p><%= link_to 'Cambiar a No completado', ruta_1_done_path(task.dones.find_by(user: current_user).id), method: :post, data: { confirm: '¿Seguro quiere borrar?' } %></p>
                        <% else %>
                          <p><%= link_to 'Completado', task_dones_path(task), class: 'btn btn-success', method: :post %></p>
                        <% end %>
                        <p><%= link_to 'Mostrar', task, class: 'btn btn-info' %></p>
                  </div>
              </div>
            </div>
          <% end %>
        </div>
    </div>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="container">



  <p>
     <%= image_tag @task.photo, class: 'card-img-top' %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @task.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @task.description %>
  </p>

  <p>
    <strong>¿Quien lo ha completado?:</strong>
    <table class="table">
      <thead>
        <th>Nombre</th>
        <th>Email</th>
      </thead>
      <% @task.users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    </table>
  </p>

  <h3>
    <%= link_to 'Back', tasks_path %>
  </h3>

</div>