config/routes.rb
Rails.application.routes.draw do

  get 'dones/create'
devise_for :users, controllers: {
  registrations: 'users/registrations'
}

  resources :tasks do
    resources :dones, only: :create
  end



  resources :dones do
    member do
      post 'ruta_1', to: 'dones#validation'
    end
  end

  root to: 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= tasks_path %>">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href= "<%= dones_path %>" >Mis Tareas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link"> Numero de Tareas Realizadas : <%= current_user.dones.count if user_signed_in?%> </a>
      </li>
    </ul>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <% if user_signed_in? %>
          <%= current_user.email %>
        <% else %>
          Ingreso
        <% end %>
      </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% if user_signed_in? %>
            <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="DELETE">Cerrar Sesión</a>
          <% else %>
            <a class="dropdown-item" href="<%= new_user_session_path %>">Iniciar Sesión</a>
            <a class="dropdown-item" href="<%= new_user_registration_path %>">Registrarse</a>
          <% end %>
        </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task18</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CDN versions of jQuery and Popper.js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <!-- bootstrapp CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end%>

    <% if alert.present? %>
      <div class="alert alert-success" role="alert">
        <%= alert %>
      </div>
    <% end%>

    <%= yield %>
  </body>
</html>